config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users, class_name: 'FormUser'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

  root                  'welcome#index'
  get     'help'    =>  'static_pages#help'
  get     'about'   =>  'static_pages#about'
  get     'contact' =>  'static_pages#contact'
  get     'signup'  =>  'users#new'
  get     'login'   =>  'sessions#new'
  post    'login'   =>  'sessions#create'
  delete  'logout'  =>  'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class = "microposts">
		<%= render @feed_items %>
	</ol>
	<div class="center">
		<%= will_paginate @feed_items %>
	</div>
<% end %>

app/views/shared/_logged_in_home.html.erb
<div class="container-fluid">
  <div class="row">
    <% cover = "image_large_2x.jpg" %>
    <%= image_tag(cover, class: "cover") %>    
  </div>
  <div class="row stats-row">
    <div class="col-md-offset-4">
      <%= render 'shared/stats' %>        
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <div class="info-avatar">
            <%= image_tag(current_user.avatar.url, class: "avatar-cover") %>
        </div>
        <div class="infor">
            <h1><%= link_to "#{@user.name}", @user %></h1>
        </div>
      </section>
    </aside>

    <div class="col-md-8 col-content">
	    <section class="micropost_form">
				<%= render 'shared/micropost_form' %>
			</section>
			<h3>Micropost Feed</h3>
			<%= render 'shared/feed' %>
		</div>
  </div>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">	
		<%= f.text_area :content, placeholder: "Compose new micropost...", class: "text-area" %>
	</div>
	<div class="btn-post-upload">
		<%= f.submit "Post", class: "btn btn-primary btn-post" %>	
		<!--<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'%>-->
	</div>
<% end %>

<script type="text/javascript">
	$('#micropost_picture').bind('change', function()) {
		var size_in_megabytes = this.file[0].size/1024/1024;
		if (size_in_megabytes > 5) {
			alert('Maximum file size is 5MB. Please choose a smaller file.')
		}
	}
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		FOLLOWING
		<strong id="following" class="stat">
			<%= @user.following.count %>
		</strong>
	</a>
	<a href="<%= followers_user_path(@user) %>">
		FOLLOWERS
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
	</a>
	<a href="<%= user_path(@user) %>">
		<% micropost = pluralize(@user.microposts.count, "micropost") %>
		<%= micropost.split(' ')[1].upcase %>
		<strong class="stat">
			<%= micropost.split(' ')[0] %>
		</strong>
	</a>
</div>

app/views/shared/_unlogged_in_home.html.erb
<div class="container">
	<div class="row">
		<div class="welcome">
			<div class="col-md-8">
				<div class="welcome-content">
					<h1>Welcome to Twitter</h1>
			  	<h3>
			    	Connect with your friends — and other fascinating people. Get in-the-moment updates on the things that interest you. And watch events unfold, in real time, from every angle.
			  	</h3>
			  	<br>
			  	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
				</div>
			</div>
			<div class="col-md-4">
				<div class="log-in-form">
					<h5>
						<strong>Log in </strong>
					</h5>
					<hr>
						<%= form_for(:session, url: login_path) do |f| %>
							<%= f.email_field :email, class: 'form-control' %>
							<%= f.password_field :password, class: 'form-control' %>
							<div class="remem-fotget">
								<%= f.label :remember_me, class: "checkbox" do %>
								<%= f.check_box :remember_me %>
								<span>Remember me</span>
								<% end %>
								<%= link_to "Forgot password?", new_password_reset_path, class: "forget-pass" %>
							</div>
						<%= f.submit "Log in", class: "btn btn-primary btn-login" %>
					<% end %>
				</div>
			</div>
		</div>	
	</div>	
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<span><h1><%= link_to "#{current_user.name}", current_user %><h1></span>