config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users, class_name: 'FormUser'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

  root                  'welcome#index'
  get     'help'    =>  'static_pages#help'
  get     'about'   =>  'static_pages#about'
  get     'contact' =>  'static_pages#contact'
  get     'signup'  =>  'users#new'
  get     'login'   =>  'sessions#new'
  post    'login'   =>  'sessions#create'
  delete  'logout'  =>  'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <div class="logo">
        <%= link_to image_tag("Twitter_logo_blue.png", size: "20x20"), root_path, id: "logo" %>
      </div>
    </div>
    
    <div class="navbar-collapse collapse" id="menu">
        <ul class="nav navbar-nav navbar-left">
          <li>
            <span class="glyphicon glyphicon-home icon"></span>
            <span><%= link_to "Home", root_path %></span>
          </li>
          <% if logged_in? %>
            <li>
              <span class="glyphicon glyphicon-bell icon"></span>
              <span> <%= link_to "Notifications", "#" %></span>
             </li>
            <li>
              <span class="glyphicon glyphicon-envelope icon"></span>
              <span><%= link_to "Messages", "#" %></span>
            </li>
            <li>
              <span class="glyphicon glyphicon-user icon"></span>
              <span><%= link_to "Users", users_path %></span>
            </li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               <%= image_tag(avatar(current_user), class: "avatar-header") %>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
              </ul>
            </li>
            <li>
              <%= button_tag(type: 'submit', class: "btn btn-primary navbar-btn") do %>
                <span class="glyphicon glyphicon-pencil" style="color: #fff;"></span> Tweet
            </li>
            <% end %>
            <% else %>
              <li><%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
      </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>

    <%= yield %>
    <div class="container">
       <%= render 'layouts/footer' %> 
    </div>  
  </body>
</html>